theme = "hugo-theme-shell"
baseURL = 'http://joshhighet.com'
languageCode = 'en-us'
title = 'josh ðŸª¿'
ignoreErrors = ["error-remote-getjson"]

[Params]
  description = "you've found me on the internet..."
  [Params.Terminal]
  scheme = "Gruvbox"
  userName = "web"
  pcName = "josh"
  workDir = ".home"
  profile = ".profile"
  description = "/description.md"
  ps1Delay = 0
  stdoutDelay = 0
  commandDelay = 30
  titleDelay = 0
  [Params.Tree]
  use = true
  folderName = "tracert"
  files = [ 
    ["keybase:joshhighet", "https://keybase.io/joshhighet"],
    ["twitter:joshhighet", "https://twitter.com/joshhighet"],
    ["whoami.joshhighet.com", "https://whoami.joshhighet.com"]
  ]

[module]
  [module.hugoVersion]
    extended = true
    min = "0.85.0"
