baseURL = 'http://joshhighet.com'
languageCode = 'en-us'
title = 'josh ðŸª¿'

[module]
[[module.imports]]
    path = 'github.com/yukuro/hugo-theme-shell'

[Params]
  description = "hello, i am josh from the internet."
  [Params.Terminal]
  scheme = "Gruvbox"
  userName = "web"
  pcName = "josh"
  workDir = ".home"
  profile = ".profile"
  description = "/desc.md"
  ps1Delay = 0
  stdoutDelay = 0
  commandDelay = 30
  titleDelay = 0
  [Params.Tree]
  use = true
  folderName = "tracert"
  files = [
    ["x:joshhighet", "https://x.com/joshhighet"],
    ["keybase:joshhighet", "https://keybase.io/joshhighet"]
  ]